### ISSUE TITLE
Better location feedback

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#6]
I think it could be useful to say exactly what the list you're currently in is of, e.g. "You are currently in the list of loops", "You are currently looking at the list of instructions for loop 2", "You are currently looking at the options for play 66".

**Comment by tjvr** [comment]
I agree that it's confusing. It should always be clear where we are in the tree.

It's most confusing after doing an actions that affects the tree structure, such as add or delete: it's not clear where we end up. These need to give _clear_ feedback.

Navigation could be improved, too: when going inside/outside nodes, we need to be clear about where we've come from and where we ended up.

In addition to announcing things like "inside loop", we might want:
- to improve the wording of "item X of Y". One user commented "Oh, it's saying 'of'?! I thought it was saying 'half', so I was ignoring it...".
- to announce what value we're changing, rather than just the value: "112".

**Comment by isaac-dunn** [comment]
I agree with all of that.

**Comment by RusticFlare** [comment]
This is very much improved and can now become issues in the future if anyone has any further ideas.
